In [1]:
! pip install pandas_profiling==2.6.0

In [6]:
import pandas as pd #for data manipulation 
import seaborn as sc #for data visualization
import matplotlib.pyplot as plt #for data Visualization
import pandas_profiling as pp #For data analysis report
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier 
import time

In [40]:
gesture_data = pd.read_csv('https://cainvas-static.s3.amazonaws.com/media/user_data/AyishaR0/gesture25_8.csv')

In [41]:
gesture_data.shape

(211, 601)

In [42]:
gesture_data['Gesture']

0      countDecrease
1      countDecrease
2      countDecrease
3      countDecrease
4      countDecrease
           ...      
206         decrease
207         decrease
208         decrease
209         decrease
210         decrease
Name: Gesture, Length: 211, dtype: object

In [44]:
values = gesture_data['Gesture'].unique()
values

array(['countDecrease', 'countIncrease', 'next', 'light', 'fan',
       'increase', 'switch', 'decrease'], dtype=object)

In [48]:
from sklearn.preprocessing import  LabelEncoder
LE = LabelEncoder()
gesture_data['Gesture'] = LE.fit_transform(gesture_data['Gesture'])
keys = gesture_data['Gesture'].unique()

In [49]:
keys

array([0, 1, 6, 5, 3, 4, 7, 2])

In [50]:
gesture_dict = dict(zip(keys, values))

In [51]:
gesture_dict

{0: 'countDecrease',
 1: 'countIncrease',
 2: 'decrease',
 3: 'fan',
 4: 'increase',
 5: 'light',
 6: 'next',
 7: 'switch'}

In [52]:
model_rf1 = RandomForestClassifier(random_state=0)

In [53]:
X = gesture_data.drop(columns=['Gesture'], axis=1)
Y = gesture_data['Gesture']

In [54]:
X

1         2         3  ...       598       599       600
0    0.079484  9.617382  2.038554  ...  0.033386 -0.042465 -0.063857
1    0.529574  9.599427  2.098407  ...  0.069166 -0.083306 -0.076423
2    1.179572  9.337273  2.668202  ... -0.109905  0.018330 -0.016268
3    1.181966  9.479722  2.826213  ... -0.109265  0.122585 -0.361493
4    1.697894  9.017660  3.776670  ... -0.055974 -0.113558 -0.240484
..        ...       ...       ...  ...       ...       ...       ...
206  0.543939  9.315726  2.754390  ... -1.056397 -0.852297 -1.011686
207  0.948541  8.973370  2.652641  ... -1.047495 -0.819136 -0.314486
208  1.050291  9.235523  2.856139  ... -1.620021 -0.637506 -0.794858
209  1.286109  8.596299  2.766360  ...  0.108086 -0.826234 -0.619162
210  1.646421  9.126593  3.344535  ... -0.996473 -1.263613 -0.756577

[211 rows x 600 columns]

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [56]:
print(X_train.shape)
print(X_test.shape)

(168, 600)
(43, 600)


In [25]:
import numpy as np

In [26]:
np.random.seed(42)
start = time.time()
print('Start time is {0: .2f}'.format(start))
param_dist = {'max_depth': [2, 3, 4],
              'bootstrap': [True, False],
                            'max_features': ['auto', 'sqrt', 'log2', None],
                            'criterion': ['gini', 'entropy']}

cv_rf = GridSearchCV(model_rf1, cv = 10,
                     param_grid=param_dist, 
                     n_jobs = 3)
cv_rf.fit(X_train, y_train)
print('Best Parameters using grid search: \n', 
      cv_rf.best_params_)
end = time.time()
print('Time taken in grid search: {0: .2f}'.format(end - start))


Start time is  1599579071.18
Best Parameters using grid search: 
 {'bootstrap': True, 'criterion': 'gini', 'max_depth': 3, 'max_features': 'log2'}
Time taken in grid search:  513.25


In [57]:
# Set best parameters given by grid search 
model_rf1.set_params(criterion = 'gini',
                     max_features = 'log2', 
                     max_depth = 3)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
model_rf1.set_params(warm_start=True, 
                  oob_score=True)

min_estimators = 15
max_estimators = 2000

error_rate = {}

for i in range(min_estimators, max_estimators + 1):
    model_rf1.set_params(n_estimators=i)
    model_rf1.fit(X_train, y_train)
    oob_error = 1 - model_rf1.oob_score_
    error_rate[i] = oob_error


In [58]:

model_rf1.set_params(n_estimators=400,
                     bootstrap = True,
                     warm_start=False,
                     oob_score=False)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [59]:
model_rf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [119]:
labels = list(gesture_dict.values())

In [107]:
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix
y_pred = model_rf1.predict(X_test)
print(len(X_test))
print(accuracy_score(y_test,y_pred))
#print(recall_score(y_test,y_pred))
conf_mat = confusion_matrix(y_test,y_pred)
print(conf_mat)

43
0.9767441860465116
[[6 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0]
 [0 0 0 2 0 0 0 0]
 [0 0 0 0 7 1 0 0]
 [0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 6]]


In [121]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test,y_pred, target_names=labels))


Classification Report

               precision    recall  f1-score   support

countDecrease       1.00      1.00      1.00         6
countIncrease       1.00      1.00      1.00         3
         next       1.00      1.00      1.00         6
        light       1.00      1.00      1.00         2
          fan       1.00      0.88      0.93         8
     increase       0.83      1.00      0.91         5
       switch       1.00      1.00      1.00         7
     decrease       1.00      1.00      1.00         6

     accuracy                           0.98        43
    macro avg       0.98      0.98      0.98        43
 weighted avg       0.98      0.98      0.98        43



In [94]:
import pickle
pickle.dump(model_rf1, open('/content/drive/My Drive/AITS/RandomForestModel.pickle', 'wb'))